In [5]:
from numpy import *
import operator
from os import listdir

In [6]:
def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels
print(createDataSet())

(array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]]), ['A', 'A', 'B', 'B'])


In [7]:
group,labels = createDataSet()
print(group)
print(labels)

[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
['A', 'A', 'B', 'B']


In [8]:
def classify0(inX, dataSet, labels, k):
    print(dataSet.shape)
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    print(tile(inX, (dataSetSize,1)))
    print(dataSet)
    print(diffMat)
    sqDiffMat = diffMat**2
    print("carre")
    print(sqDiffMat)
    sqDistances = sqDiffMat.sum(axis=1)
    print("distance")
    print(sqDistances)
    distances = sqDistances**0.5
    print("racine distance")
    print(distances)
    sortedDistIndicies = distances.argsort()     
    print(sortedDistIndicies)
    print(distances)
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

classify0([0,0], group, labels, 3)

(4, 2)
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
[[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]
carre
[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]
distance
[2.21 2.   0.   0.01]
racine distance
[1.48660687 1.41421356 0.         0.1       ]
[2 3 1 0]
[1.48660687 1.41421356 0.         0.1       ]


'B'

In [13]:
def file2matrix(filename):
    fr = open(filename)
    numberOfLines = len(fr.readlines())         #get the number of lines in the file
    returnMat = zeros((numberOfLines,3))        #prepare matrix to return
    classLabelVector = []                       #prepare labels return   
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(listFromLine[-1])
        index += 1
    return returnMat,classLabelVector
inputMat, classLabelVector = file2matrix("datingTestSet.txt")
print(inputMat[0 :5])
print(classLabelVector[0 :5])

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 [7.5136000e+04 1.3147394e+01 4.2896400e-01]
 [3.8344000e+04 1.6697880e+00 1.3429600e-01]]
['largeDoses', 'smallDoses', 'didntLike', 'didntLike', 'didntLike']
